services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: expense_tracker
    volumes:
      - expense-app:/var/lib/mysql

  backend:
    build:
      context: ./backend
    restart: always
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "80:80"

volumes:
  expense-app:
