services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: expense_tracker
    volumes:
      - expense-app:/var/lib/mysql

  backend:
    build:
      context: ./backend
    environment:
      DB_NAME: expense_tracker
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_HOST: database
      DB_DIALECT: mysql
      TOKEN_KEY: inikunciku
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    environment:
      BACKEND_URL: backend:3000
    ports:
      - "80:80"

volumes:
  expense-app:
